server:
  port: 9191

spring:
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackOff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
            redis-rate-limiter.requestedTokens: 1
            denyEmptyKey: false
      redis:
        connect-timeout: 30s
        host: localhost
        port: 6379
        timeout: 5s
      routes:
        - id: AUTHENTICATION-SERVICE
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/auth-fallback
        - id: IMAGES-SERVICE
          uri: lb://IMAGES-SERVICE
          predicates:
            - Path=/images/**
          filters:
            - name: CircuitBreaker
              args:
                name: imagesCircuitBreaker
                fallbackUri: forward:/images-fallback
        - id: CONFIG-SERVICE
          uri: http://${app.config-server}:8888
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/(?<segment>.*), /$\{segment}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"