server:
  port: 8084

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
    instance:
      hostname: localhost

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://registry:8084/eureka/
    fetch-registry: false


