server:
  port: 9001


spring:
  application:
    name: IMAGES-SERVICE


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
  instance:
    hostname: localhost
---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://registry:8084/eureka
    fetch-registry: true
  instance:
    preferIpAddress: true