version: '3'
services:
  react-front:
    image: reactimage:latest
    ports:
      - 3000:3000
    profiles:
      - docker
    depends_on:
      - gateway-service
      - login-service
  registry:
    image: registryimage:latest
    ports:
      - 8084:8084
    profiles:
      - docker
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    depends_on:
      config-service:
        condition: service_healthy
    restart: on-failure
  gateway-service:
    image: gatewayimage:latest
    container_name: gatewaycontainer
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://registry:8084/eureka
      - "SPRING_PROFILES_ACTIVE=docker"
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    ports:
      - 9191:9191
    depends_on:
      - registry
      - config-service
    profiles:
      - docker
  db:
    container_name: dbcontainer
    image: 'mysql:8'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nasausers
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3301:3306'
    restart: always
    profiles:
      - docker
    volumes:
      - my-datavolume:/var/lib/mysql
  login-service:
    image: loginimage:latest
    environment:
      - JAVA_OPTS=-DEUREKA_SERVER=http://registry:8084/eureka
      - "SPRING_PROFILES_ACTIVE=docker"
      - CONFIG_SERVICE_USR=${CONFIG_SERVICE_USR}
      - CONFIG_SERVICE_PWD=${CONFIG_SERVICE_PWD}
    ports:
      - 9000:9000
    depends_on:
      - db
      - registry
      - config-service
    profiles:
      - docker
  images-service:
    image: imagesimage:latest
    environment:
      - JAVA_OPTS=-DEUREKA_SERVER=http://registry:8084/eureka
      - "SPRING_PROFILES_ACTIVE=docker"
      - CONFIG_SERVER_USR=${CONFIG_SERVER_USR}
      - CONFIG_SERVER_PWD=${CONFIG_SERVER_PWD}
    ports:
      - 9001:9001
    depends_on:
      - registry
      - db
      - config-service
    profiles:
      - docker
  config-service:
    image: configimage:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=docker,native"
      - ENCRYPT_KEY=${CONFIG_SERVICE_ENCRYPT_KEY}
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVICE_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVICE_PWD}
    ports:
      - 8888:8888
    volumes:
      - C:/Users/Fernando/Desktop/git/NASA-webapp/config-repo:/config-repo
    mem_limit: 350m
    profiles:
      - docker
    healthcheck:
      test: "exit 0"


volumes:
  my-datavolume:
  