server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: AUTHENTICATION-SERVICE
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**
        - id: IMAGES-SERVICE
          uri: lb://IMAGES-SERVICE
          predicates:
            - Path=/images/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
    instance:
      hostname: localhost

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://registry:8084/eureka
    fetch-registry: true
  instance:
    preferIpAddress: true