spring.application.name: configuration-service
server.port: 8888
spring:
  profiles:
    active: native

spring.cloud.config.server.native.searchLocations: file:C:/Users/Fernando/Desktop/git/NASA-webapp/config-repo

logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: docker
spring.cloud.config.server.native.searchLocations: file:/config-repo

